# Generated by Django 6.1 on 2026-09-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JWTBlacklist',
            fields=[
                ('jti', models.CharField(db_index=True, max_length=64, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'JWT Blacklist Entry',
                'verbose_name_plural': 'JWT Blacklist Entries',
                'db_table': '_0041_jwt_blacklist',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('crt_at', models.DateTimeField(auto_now_add=True)),
                ('upd_at', models.DateTimeField(auto_now=True)),
                ('change_pw_at', models.DateTimeField(auto_now_add=True)),
                ('gen_id', models.CharField(db_index=True, max_length=8, unique=True)),
                ('knox_id', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('full_name', models.CharField(max_length=50)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Waiting'), (1, 'Approval'), (2, 'Reject'), (3, 'Block'), (4, 'Deleted')], default=0)),
                ('ip_remember', models.CharField(blank=True, max_length=15, null=True)),
                ('password', models.CharField(help_text='Hashed password (PBKDF2-SHA256).', max_length=128)),
                ('failed_login_attempts', models.PositiveSmallIntegerField(default=0, help_text='Count of consecutive failed login attempts.')),
                ('locked_until', models.DateTimeField(blank=True, help_text='Account locked until this time (NULL = not locked).', null=True)),
            ],
            options={
                'db_table': '_0010_user',
                'ordering': ['-crt_at'],
            },
        ),
    ]
