# Generated by Django 6.1 on 2026-08-29 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='org',
            field=models.ForeignKey(db_column='org_id', on_delete=django.db.models.deletion.PROTECT, related_name='users', to='info.organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='shift',
            field=models.ForeignKey(db_column='shift_id', on_delete=django.db.models.deletion.PROTECT, related_name='users', to='info.shift'),
        ),
    ]
