# Generated by Django 6.0.7 on 2026-10-02 20:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshTokenSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('family_id', models.UUIDField(db_index=True)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('absolute_expires_at', models.DateTimeField(db_index=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_name', models.CharField(blank=True, default='', max_length=120)),
                ('crt_at', models.DateTimeField(auto_now_add=True)),
                ('upd_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounts.refreshtokensession')),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='accounts.refreshtokensession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_sessions', to='accounts.user')),
            ],
            options={
                'verbose_name': 'Refresh Token Session',
                'verbose_name_plural': 'Refresh Token Sessions',
                'db_table': '_0042_refresh_token_session',
                'ordering': ['-last_used_at', '-crt_at'],
                'indexes': [models.Index(fields=['user', 'revoked_at'], name='idx_rt_user_revoked'), models.Index(fields=['family_id', 'revoked_at'], name='idx_rt_family_revoked')],
            },
        ),
    ]
