# Generated by Django 6.1 on 2026-08-30 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JWTBlacklist',
            fields=[
                ('jti', models.CharField(db_index=True, max_length=64, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'JWT Blacklist Entry',
                'verbose_name_plural': 'JWT Blacklist Entries',
                'db_table': '_0041_jwt_blacklist',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Count of consecutive failed login attempts.'),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, help_text='Account locked until this time (NULL = not locked).', null=True),
        ),
    ]
