# Generated by Django 6.0.7 on 2026-10-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmember',
            name='is_favorite',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
