# Generated by Django 6.1 on 2026-09-06 05:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('embedding', models.TextField()),
                ('image_path', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_embeddings', to='accounts.user')),
            ],
            options={
                'db_table': 'face_embeddings',
                'indexes': [models.Index(fields=['user', '-created_at'], name='face_embedd_user_id_3c6868_idx')],
            },
        ),
    ]
