# Generated by Django 6.1 on 2026-08-29 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupHeader',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sort', models.PositiveSmallIntegerField(default=1)),
                ('is_use', models.BooleanField(default=True)),
                ('group_vi', models.CharField(max_length=25)),
                ('group_en', models.CharField(max_length=25)),
                ('group_kr', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Group Header',
                'verbose_name_plural': 'Group Headers',
                'db_table': '_0030_group_header',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_code', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('model', models.CharField(blank=True, max_length=8, null=True)),
                ('model_full', models.CharField(blank=True, max_length=15, null=True)),
                ('part_name', models.CharField(max_length=50)),
                ('part_name_full', models.CharField(max_length=125)),
                ('color', models.CharField(blank=True, max_length=25, null=True)),
                ('group', models.IntegerField()),
                ('is_manual', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'db_table': '_0021_info_material',
                'ordering': ['material_code'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('shift_vi', models.CharField(max_length=25)),
                ('shift_en', models.CharField(max_length=25)),
                ('shift_kr', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
                'db_table': '_0006_shift',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=125)),
                ('is_use', models.BooleanField(default=True)),
                ('is_replace', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'db_table': '_0020_info_vendor',
                'ordering': ['vendor_code'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'Team'), (1, 'Group'), (2, 'Part'), (3, 'Location')], default=0)),
                ('sort', models.IntegerField(default=0)),
                ('is_use', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='info.organization')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': '_0000_organizations',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HeaderRegistration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('crt_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, db_column='apr_at', null=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Cần đăng ký'), (1, 'Không cần đăng ký')], default=0)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending Approval'), (1, 'Approval'), (2, 'Rejected')], default=0)),
                ('approved_by', models.ForeignKey(blank=True, db_column='apr_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='header_registrations_approved', to='accounts.user')),
                ('registered_by', models.ForeignKey(db_column='rgt_id', on_delete=django.db.models.deletion.PROTECT, related_name='header_registrations', to='accounts.user')),
                ('org', models.ForeignKey(db_column='org_id', on_delete=django.db.models.deletion.CASCADE, related_name='header_registrations', to='info.organization')),
            ],
            options={
                'verbose_name': 'Header Registration',
                'verbose_name_plural': 'Header Registrations',
                'db_table': '_0035_header_registration',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HeaderOrganization',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('crt_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, db_column='apr_at', null=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Cần đăng ký'), (1, 'Không cần đăng ký')], default=0)),
                ('is_selected', models.BooleanField(default=False)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending Approval'), (1, 'Approval'), (2, 'Rejected')], default=0)),
                ('approved_by', models.ForeignKey(blank=True, db_column='apr_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='header_organizations_approved', to='accounts.user')),
                ('registered_by', models.ForeignKey(db_column='rgt_id', on_delete=django.db.models.deletion.PROTECT, related_name='header_organizations', to='accounts.user')),
                ('header_registration', models.ForeignKey(db_column='header_registration_id', on_delete=django.db.models.deletion.CASCADE, related_name='organization_assignments', to='info.headerregistration')),
                ('org', models.ForeignKey(db_column='org_id', on_delete=django.db.models.deletion.CASCADE, related_name='header_organizations', to='info.organization')),
            ],
            options={
                'verbose_name': 'Header Organization',
                'verbose_name_plural': 'Header Organizations',
                'db_table': '_0037_header_organizations',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PagesHeader',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_use', models.BooleanField(default=True)),
                ('sort', models.PositiveSmallIntegerField(default=1)),
                ('page_vi', models.CharField(max_length=50)),
                ('page_en', models.CharField(max_length=50)),
                ('page_kr', models.CharField(max_length=50)),
                ('group_header', models.ForeignKey(db_column='group_header_id', on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='info.groupheader')),
            ],
            options={
                'verbose_name': 'Pages Header',
                'verbose_name_plural': 'Pages Headers',
                'db_table': '_0031_pages_header',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SystemHeader',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sort', models.PositiveSmallIntegerField(default=1)),
                ('is_use', models.BooleanField(default=True)),
                ('is_mobile', models.BooleanField(default=False)),
                ('view_vi', models.CharField(max_length=75)),
                ('view_en', models.CharField(max_length=75)),
                ('view_kr', models.CharField(max_length=75)),
                ('header_vi', models.CharField(max_length=75)),
                ('header_en', models.CharField(max_length=75)),
                ('header_kr', models.CharField(max_length=75)),
                ('page_header', models.ForeignKey(db_column='page_header_id', on_delete=django.db.models.deletion.CASCADE, related_name='system_headers', to='info.pagesheader')),
            ],
            options={
                'verbose_name': 'System Header',
                'verbose_name_plural': 'System Headers',
                'db_table': '_0032_system_header',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.AddField(
            model_name='headerregistration',
            name='header',
            field=models.ForeignKey(db_column='header_id', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='info.systemheader'),
        ),
        migrations.CreateModel(
            name='SystemPower',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_use', models.BooleanField(default=True)),
                ('sort', models.PositiveSmallIntegerField(default=1)),
                ('power_vi', models.CharField(max_length=75)),
                ('power_en', models.CharField(max_length=75)),
                ('power_kr', models.CharField(max_length=75)),
                ('system_header', models.ForeignKey(db_column='system_header_id', on_delete=django.db.models.deletion.CASCADE, related_name='powers', to='info.systemheader')),
            ],
            options={
                'verbose_name': 'System Power',
                'verbose_name_plural': 'System Powers',
                'db_table': '_0033_system_power',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SystemPermission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('crt_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, db_column='apr_at', null=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Cần đăng ký'), (1, 'Không cần đăng ký')], default=0)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending Approval'), (1, 'Approval'), (2, 'Rejected')], default=0)),
                ('approved_by', models.ForeignKey(blank=True, db_column='apr_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='system_permissions_approved', to='accounts.user')),
                ('org', models.ForeignKey(db_column='org_id', on_delete=django.db.models.deletion.CASCADE, related_name='system_permissions', to='info.organization')),
                ('registered_by', models.ForeignKey(db_column='rgt_id', on_delete=django.db.models.deletion.PROTECT, related_name='system_permissions', to='accounts.user')),
                ('power', models.ForeignKey(db_column='power_id', on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='info.systempower')),
            ],
            options={
                'verbose_name': 'System Permission',
                'verbose_name_plural': 'System Permissions',
                'db_table': '_0039_system_permissions',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserHeaderRegistration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('crt_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, db_column='apr_at', null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending Approval'), (1, 'Approval'), (2, 'Rejected')], default=0)),
                ('approved_by', models.ForeignKey(blank=True, db_column='apr_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_header_registrations_approved', to='accounts.user')),
                ('header_registration', models.ForeignKey(db_column='header_registration_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_registrations', to='info.headerregistration')),
                ('registered_by', models.ForeignKey(db_column='rgt_id', on_delete=django.db.models.deletion.PROTECT, related_name='user_header_registrations', to='accounts.user')),
            ],
            options={
                'verbose_name': 'User Header Registration',
                'verbose_name_plural': 'User Header Registrations',
                'db_table': '_0036_user_header_registration',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserSystemPermissionRegistration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('crt_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, db_column='apr_at', null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending Approval'), (1, 'Approval'), (2, 'Rejected')], default=0)),
                ('approved_by', models.ForeignKey(blank=True, db_column='apr_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_system_permission_registrations_approved', to='accounts.user')),
                ('registered_by', models.ForeignKey(db_column='rgt_id', on_delete=django.db.models.deletion.PROTECT, related_name='user_system_permission_registrations', to='accounts.user')),
                ('system_permission', models.ForeignKey(db_column='system_permission_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_registrations', to='info.systempermission')),
            ],
            options={
                'verbose_name': 'User System Permission Registration',
                'verbose_name_plural': 'User System Permission Registrations',
                'db_table': '_0040_user_system_permissions_registration',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HeaderOrganizationUserRegistration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('crt_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, db_column='apr_at', null=True)),
                ('is_selected', models.BooleanField(default=False)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending Approval'), (1, 'Approval'), (2, 'Rejected')], default=0)),
                ('approved_by', models.ForeignKey(blank=True, db_column='apr_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='header_org_user_registrations_approved', to='accounts.user')),
                ('header_organization', models.ForeignKey(db_column='header_organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_registrations', to='info.headerorganization')),
                ('registered_by', models.ForeignKey(db_column='rgt_id', on_delete=django.db.models.deletion.PROTECT, related_name='header_org_user_registrations', to='accounts.user')),
            ],
            options={
                'verbose_name': 'Header Organization User Registration',
                'verbose_name_plural': 'Header Organization User Registrations',
                'db_table': '_0038_header_organization_user_registration',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('registered_by', 'header_organization'), name='uq_0038_user_header_organization')],
            },
        ),
        migrations.AddConstraint(
            model_name='headerorganization',
            constraint=models.UniqueConstraint(fields=('org', 'header_registration'), name='uq_0037_org_header_registration'),
        ),
        migrations.AddConstraint(
            model_name='headerregistration',
            constraint=models.UniqueConstraint(fields=('org', 'header'), name='uq_0035_org_header'),
        ),
        migrations.AddConstraint(
            model_name='systempermission',
            constraint=models.UniqueConstraint(fields=('org', 'power'), name='uq_0039_org_power'),
        ),
        migrations.AddConstraint(
            model_name='userheaderregistration',
            constraint=models.UniqueConstraint(fields=('registered_by', 'header_registration'), name='uq_0036_user_header_registration'),
        ),
        migrations.AddConstraint(
            model_name='usersystempermissionregistration',
            constraint=models.UniqueConstraint(fields=('registered_by', 'system_permission'), name='uq_0040_user_system_permission'),
        ),
    ]
