# Generated by Django 6.0.7 on 2026-09-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Company'), (1, 'Team'), (2, 'Group'), (3, 'Part'), (4, 'Location')], default=0),
        ),
    ]
