# Generated by Django 6.1 on 2026-08-30 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='cached_full_name',
            field=models.CharField(blank=True, help_text="Denormalized: 'SET QC Team => IQC G => ...'", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='cached_full_path',
            field=models.CharField(blank=True, db_index=True, help_text="Denormalized: '1.2.4.22.'", max_length=255, null=True),
        ),
    ]
