# Generated by Django 6.1 on 2026-09-12 17:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(blank=True, default='', help_text='Phân loại FAQ (vd: Hệ thống, Tài khoản, Dữ liệu QC)', max_length=100)),
                ('question', models.CharField(help_text='Câu hỏi', max_length=500)),
                ('answer', models.TextField(help_text='Câu trả lời')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Chỉ FAQ đang active mới hiển thị')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Thứ tự hiển thị (nhỏ hơn = trước)')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'db_table': 'ai_faq',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
